# Generated by Django 6.0 on 2026-01-13 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0005_alter_payment_payment_type_alter_payment_total_sum"),
    ]

    operations = [
        migrations.AlterField(
            model_name="payment",
            name="link",
            field=models.URLField(
                blank=True,
                help_text="Укажите ссылку на оплату",
                max_length=1000,
                null=True,
                verbose_name="Ссылка на оплату",
            ),
        ),
    ]
