# Generated by Django 6.0 on 2026-01-12 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("course", "0003_course_owner_lesson_owner"),
    ]

    operations = [
        migrations.AddField(
            model_name="course",
            name="stripe_product_id",
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name="Id курса в Stripe"),
        ),
        migrations.AddField(
            model_name="lesson",
            name="stripe_product_id",
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name="Id урока в Stripe"),
        ),
    ]
