# Generated by Django 6.0 on 2026-01-12 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("course", "0004_course_stripe_product_id_lesson_stripe_product_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="course",
            name="price",
            field=models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name="Цена курса"),
        ),
        migrations.AddField(
            model_name="lesson",
            name="price",
            field=models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name="Цена урока"),
        ),
    ]
